services:
  backapp:
    build: ./backapp
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081

  frontapp:
    build: ./frontapp
    ports:
      - "8080:8080"
    environment:
      - BACK_URL=http://backapp:8081
